image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t my-fastapi-app -f api/Dockerfile .

deploy:
  stage: deploy
  script:
    - docker run -d -p 8000:8000 my-fastapi-app
    - sleep 5 # wait for the container to be up
    - docker ps -a # check if the container is running
