include:
  - local: 'deploy_train/.gitlab-ci.yml'
  - local: 'deploy_serve/.gitlab-ci.yml'

stages:
  - build
  - deploy_train
  - deploy_serve

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "exp"'
    - if: '$CI_COMMIT_BRANCH == "main"'

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info
