image: ruby:3.1

stages:
  - test

job-to-run-the-code:
  script:
    - apt-get update
    - apt-get install -y python3 python3-pip
    - python3 --version  # Check Python version
    - ruby --version  # Check Ruby version
    - python3 hello.py
