image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker info
    - docker build -t my-fastapi-app:latest -f api/Dockerfile api/
    - docker save my-fastapi-app:latest -o my-fastapi-app.tar
  artifacts:
    paths:
      - my-fastapi-app.tar
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "exp"'
    - if: '$CI_COMMIT_BRANCH == "working"'

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  dependencies:
    - build
  script:
    - docker load -i my-fastapi-app.tar
    - docker run -d -p 5000:5000 my-fastapi-app:latest
    - sleep 5 # wait for the container to be up
    - docker ps -a # check if the container is running
  tags:
    - localrunner
    - localshell
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
