image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t my-fastapi-app .

deploy:
  stage: deploy
  script:
    - docker run -d -p 80:80 --name my-fastapi-app my-fastapi-app
  only:
    - main
