apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: NodePort
  selector:
    app: fastapi-app
  ports:
    - port: 80
      targetPort: 8000  # Assuming FastAPI listens on port 8000 inside the pod
      nodePort: 30001    # Choose a port number (30001-32767) for NodePort
